"use strict";
const http = require("node:http");
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const { DatabaseSync } = require("node:sqlite");
const PORT = Number(process.env.PORT || 3000), ROOT = __dirname;
const SECRET = process.env.SESSION_SECRET || "replace-this-secret-before-production";
fs.mkdirSync(path.join(ROOT, "data"), { recursive: true });
const db = new DatabaseSync(path.join(ROOT, "data", "finance-buddy.sqlite"));
db.exec(`PRAGMA journal_mode = WAL;
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, full_name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('parent','child')), everyday_cents INTEGER NOT NULL DEFAULT 0, emergency_cents INTEGER NOT NULL DEFAULT 0, savings_cents INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS transactions (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), type TEXT NOT NULL, amount_cents INTEGER NOT NULL, note TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS approvals (id INTEGER PRIMARY KEY, child_id INTEGER NOT NULL REFERENCES users(id), amount_cents INTEGER NOT NULL, reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')), reviewed_by INTEGER REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`);
function send(res, status, body, type = "application/json; charset=utf-8") { res.writeHead(status, { "Content-Type": type, "Cache-Control": "no-store" }); res.end(type.startsWith("application/json") ? JSON.stringify(body) : body); }
function bad(res, message, status = 400) { send(res, status, { error: message }); }
function parseJson(req) { return new Promise((resolve, reject) => { let body = ""; req.on("data", c => { body += c; if (body.length > 100000) req.destroy(); }); req.on("end", () => { try { resolve(body ? JSON.parse(body) : {}); } catch { reject(new Error("Invalid JSON body.")); } }); req.on("error", reject); }); }
function hashPassword(password, salt = crypto.randomBytes(16).toString("hex")) { return new Promise((resolve, reject) => crypto.scrypt(password, salt, 64, (e, key) => e ? reject(e) : resolve(`${salt}:${key.toString("hex")}`))); }
async function passwordMatches(password, stored) { const [salt, expected] = stored.split(":"); const actual = await hashPassword(password, salt); return crypto.timingSafeEqual(Buffer.from(actual.split(":")[1], "hex"), Buffer.from(expected, "hex")); }
function tokenFor(user) { const payload = Buffer.from(JSON.stringify({ id: user.id, role: user.role, exp: Date.now() + 7 * 86400000 })).toString("base64url"); return `${payload}.${crypto.createHmac("sha256", SECRET).update(payload).digest("base64url")}`; }
function currentUser(req) { const match = (req.headers.authorization || "").match(/^Bearer (.+)$/); if (!match) return null; const [payload, signature] = match[1].split("."); if (!payload || !signature) return null; const expected = crypto.createHmac("sha256", SECRET).update(payload).digest("base64url"); if (signature.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; try { const session = JSON.parse(Buffer.from(payload, "base64url").toString()); if (session.exp < Date.now()) return null; return db.prepare("SELECT id, full_name, email, role, everyday_cents, emergency_cents, savings_cents FROM users WHERE id = ?").get(session.id) || null; } catch { return null; } }
function requireUser(req, res) { const user = currentUser(req); if (!user) { bad(res, "Please sign in to continue.", 401); return null; } return user; }
function publicUser(user) { return { id: user.id, fullName: user.full_name, email: user.email, role: user.role }; }
function asCents(value) { const n = Number(value); return Number.isFinite(n) && n > 0 ? Math.round(n * 100) : 0; }
async function api(req, res, pathname) {
  if (req.method === "POST" && pathname === "/api/auth/register") { const { fullName, email, password, role } = await parseJson(req), name = String(fullName || "").trim(), cleanEmail = String(email || "").trim().toLowerCase(); if (name.length < 2) return bad(res, "Enter a name with at least 2 characters."); if (!/^\S+@\S+\.\S+$/.test(cleanEmail)) return bad(res, "Enter a valid email address."); if (String(password || "").length < 8) return bad(res, "Password must be at least 8 characters."); if (!["parent", "child"].includes(role)) return bad(res, "Select Parent or Child."); try { const result = db.prepare("INSERT INTO users (full_name, email, password_hash, role) VALUES (?, ?, ?, ?)").run(name, cleanEmail, await hashPassword(password), role), user = db.prepare("SELECT * FROM users WHERE id = ?").get(result.lastInsertRowid); return send(res, 201, { token: tokenFor(user), user: publicUser(user) }); } catch (e) { return bad(res, e.message.includes("UNIQUE") ? "An account already exists for this email." : "Could not create account."); } }
  if (req.method === "POST" && pathname === "/api/auth/login") { const { email, password, role } = await parseJson(req), user = db.prepare("SELECT * FROM users WHERE email = ?").get(String(email || "").trim().toLowerCase()); if (!user || user.role !== role || !(await passwordMatches(String(password || ""), user.password_hash))) return bad(res, "Email, password, or account type is incorrect.", 401); return send(res, 200, { token: tokenFor(user), user: publicUser(user) }); }
  if (req.method === "GET" && pathname === "/api/me") { const user = requireUser(req, res); if (user) send(res, 200, { user: publicUser(user) }); return; }
  if (req.method === "GET" && pathname === "/api/dashboard") { const user = requireUser(req, res); if (!user) return; const pending = db.prepare("SELECT * FROM approvals WHERE status = 'pending' ORDER BY id DESC LIMIT 1").get(), total = user.everyday_cents + user.emergency_cents + user.savings_cents; return send(res, 200, { user: publicUser(user), balances: { everyday: user.everyday_cents, emergency: user.emergency_cents, savings: user.savings_cents, total }, pendingApproval: pending && { id: pending.id, amount: pending.amount_cents, reason: pending.reason }, goal: { current: user.savings_cents, target: Math.max(user.savings_cents, 80000) } }); }
  if (req.method === "POST" && pathname === "/api/funds") { const user = requireUser(req, res); if (!user) return; if (user.role !== "parent") return bad(res, "Only a parent can fund a wallet.", 403); const { amount, note } = await parseJson(req), cents = asCents(amount); if (!cents) return bad(res, "Enter a positive funding amount."); const everyday = Math.round(cents * .5), emergency = Math.round(cents * .2), savings = cents - everyday - emergency; db.prepare("UPDATE users SET everyday_cents = everyday_cents + ?, emergency_cents = emergency_cents + ?, savings_cents = savings_cents + ? WHERE id = ?").run(everyday, emergency, savings, user.id); db.prepare("INSERT INTO transactions (user_id, type, amount_cents, note) VALUES (?, 'fund', ?, ?)").run(user.id, cents, String(note || "Wallet funded")); return send(res, 201, { message: "Wallet funded and allocated across all three buckets." }); }
  if (req.method === "POST" && pathname === "/api/approvals") { const user = requireUser(req, res); if (!user) return; if (user.role !== "child") return bad(res, "Only a child account can request an approval.", 403); const { amount, reason } = await parseJson(req), cents = asCents(amount); if (!cents || String(reason || "").trim().length < 4) return bad(res, "Include a positive amount and a short reason."); db.prepare("INSERT INTO approvals (child_id, amount_cents, reason) VALUES (?, ?, ?)").run(user.id, cents, String(reason).trim()); return send(res, 201, { message: "Your request is ready for a parent to review." }); }
  if (req.method === "POST" && /^\/api\/approvals\/\d+\/review$/.test(pathname)) { const user = requireUser(req, res); if (!user) return; if (user.role !== "parent") return bad(res, "Only a parent can review requests.", 403); const id = Number(pathname.split("/")[3]), { decision } = await parseJson(req); if (!["approved", "rejected"].includes(decision)) return bad(res, "Choose approved or rejected."); const result = db.prepare("UPDATE approvals SET status = ?, reviewed_by = ? WHERE id = ? AND status = 'pending'").run(decision, user.id, id); if (!result.changes) return bad(res, "This request is no longer pending.", 404); return send(res, 200, { message: `Request ${decision}.` }); }
  return bad(res, "API endpoint not found.", 404);
}
function page(file) { return fs.readFileSync(path.join(ROOT, file), "utf8").replace("</body>", '<script src="/client.js" defer></script></body>'); }
http.createServer(async (req, res) => { const pathname = new URL(req.url, `http://${req.headers.host}`).pathname; try { if (pathname.startsWith("/api/")) return await api(req, res, pathname); const routes = { "/": "login.html", "/login": "login.html", "/login.html": "login.html", "/register": "register.html", "/register.html": "register.html", "/dashboard": "dashboard.html", "/dashboard.html": "dashboard.html" }; if (routes[pathname]) return send(res, 200, page(routes[pathname]), "text/html; charset=utf-8"); if (pathname === "/client.js") return send(res, 200, fs.readFileSync(path.join(ROOT, "client.js"), "utf8"), "application/javascript; charset=utf-8"); return send(res, 404, "Not found", "text/plain; charset=utf-8"); } catch (e) { console.error(e); return bad(res, "Unexpected server error.", 500); } }).listen(PORT, () => console.log(`FinanceBuddy is running at http://localhost:${PORT}`));
